---
name: 'Test upgrade'

on:
  release:
    types: [prereleased]

permissions:
  id-token: write
  contents: read

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Prerelease tag used: ${{ github.ref_name }}"
        run: exit 0
