---
name: 'Test upgrade'

on:
  release:
    types: [prereleased]

permissions:
  id-token: write
  contents: read

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Print tag to be used"
        run: echo "Using prerelease tag "${{ github.ref_name }}
